#:schema node_modules/wrangler/config-schema.json
name = "characters-api"
main = "src/index.ts"
compatibility_date = "2024-05-02"

[[unsafe.bindings]]
name = "MY_RATE_LIMITER"
type = "ratelimit"
namespace_id = "9114"
simple = { limit = 30, period = 60 }